// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlUkpVxugwwPt4CKPIAyHspibrLIMorTE',
    appId: '1:805952168001:web:598b64b1122858ca5726c0',
    messagingSenderId: '805952168001',
    projectId: 'bejan-singh-eye-hospital',
    authDomain: 'bejan-singh-eye-hospital.firebaseapp.com',
    storageBucket: 'bejan-singh-eye-hospital.firebasestorage.app',
    measurementId: 'G-XQVY6M1FCV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhbQRG7WTef9myE6F5wkfKRyiy2DlO78I',
    appId: '1:805952168001:android:d23d457a971ef8b75726c0',
    messagingSenderId: '805952168001',
    projectId: 'bejan-singh-eye-hospital',
    storageBucket: 'bejan-singh-eye-hospital.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnAWcdqH5p72TtaGDAPCTC-pveDCLEh6c',
    appId: '1:805952168001:ios:00e64a9d791fdbb95726c0',
    messagingSenderId: '805952168001',
    projectId: 'bejan-singh-eye-hospital',
    storageBucket: 'bejan-singh-eye-hospital.firebasestorage.app',
    iosBundleId: 'com.example.campOrganizer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnAWcdqH5p72TtaGDAPCTC-pveDCLEh6c',
    appId: '1:805952168001:ios:00e64a9d791fdbb95726c0',
    messagingSenderId: '805952168001',
    projectId: 'bejan-singh-eye-hospital',
    storageBucket: 'bejan-singh-eye-hospital.firebasestorage.app',
    iosBundleId: 'com.example.campOrganizer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlUkpVxugwwPt4CKPIAyHspibrLIMorTE',
    appId: '1:805952168001:web:da6041e074d76eb45726c0',
    messagingSenderId: '805952168001',
    projectId: 'bejan-singh-eye-hospital',
    authDomain: 'bejan-singh-eye-hospital.firebaseapp.com',
    storageBucket: 'bejan-singh-eye-hospital.firebasestorage.app',
    measurementId: 'G-WRWDLESPS8',
  );
}
